CC = gcc
CFLAGS=-Wall -Wextra
TARGET=SimpleCache

# $(CC) $(CFLAGS) SimpleProgram.c SimpleCache.c -o $(TARGET)
all:
	$(CC) $(CFLAGS) ../tests/SimpleProgram.c ../task2/L2Cache.c -o $(TARGET)

clean:
	rm $(TARGET)